### ISSUE TITLE
Could you introduce rendertri's main algorithms?

### ISSUE THREAD

**Issue by WilliamWangPeng** [felipetavares/rendertri#1]
Hi dear author,  
    I could not find some algorithms introduced here, Could you introduce rendertri's main algorithms?  

thank you  
best regards  
William

**Comment by felipetavares** [comment]
The way rendertri works is:

- read a file describing a lot of triangles (in itself described by two x/y/z vectors, one for the position and one for the normal)
- multiply each of the positions/normals by a matrix, this is used to rotate the triangles (and consequently the whole model). [Wikipedia](https://en.wikipedia.org/wiki/Rotation_matrix)
- do a perspective transformation on those positions, which is mapping them from a 3d world to a 2d screen by dividing each position by it's z coordinate: (x, y, z) becomes (x/z, y/z)
- figure out the colors of each pixel and draw that to a screen using a triangle rasterization algorithm.  [Wikipedia](https://en.wikipedia.org/wiki/Rasterisation#Triangle_rasterization)

There's only one big algorithm, which is the one for figuring out which pixels are inside a triangle for the triangle rasterization. Everything else is just a matter of finding the positions and colors of those triangles.

Any further questions?

**Comment by felipetavares** [comment]
There's a much better implementation of a triangle rasterization algorithm here:

https://github.com/nibbleteam/nibble/blob/dc66fa9a40aec32c2c4f536975496a612ca91d8e/src/devices/GPU.cpp#L619
